server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
    waitTimeInMsWhenSyncEmpty: 0

spring:
  application:
    name: eureka-server
#  security:
#    user:
#      name: 'randolph'
#      password: '031125'

logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO
