spring:
  application:
    name: authentication-service

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: 
    password: 
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false
      database: postgresql
      dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: 
            client-id: 
            client-secret: 

          github:
            redirect-uri:
            client-id: 
            client-secret:

frontend:
  url: http://localhost:3000

randolph:
  app:
    jwtSecret:
    jwtExpirationMs: 960000

server:
  port: 8080


logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security.oauth2: TRACE

eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

